"""whatsapp link column remove

Revision ID: add0e638bba8
Revises: bfaebab1b597
Create Date: 2026-03-07 17:14:08.162454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add0e638bba8'
down_revision = 'bfaebab1b597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
